- composer.json
Plugins themselves don't actually depend on the plugin installer, only
apps using plugins do (arguably, even then they don't)
Would be a good idea to let some time pass after 216 is merged, so that users still have a reference to the plugin installer.
Depends on cakephp/app#216
> plugin installer is required by cakephp/app

- src/Shell/Task/MigrationSnapshotTask.php
- src/Shell/Task/MigrationTask.php
- src/Shell/Task/SimpleMigrationTask.php
- src/View/Helper/MigrationHelper.php
- tests/TestCase/View/Helper/MigrationHelperTest.php
This can be useful in cases where the database hasn't yet been setup. For instance, on a fresh `composer create-project`, I hadn't yet created the database `my_app`, so my cli migration generation failed, even though a db connection was not required.
> Allow generating migrations without a db connection

- composer.json
We depend on a constant which had been added in 0.4.2, hence bumping required version to `^0.4.2` which is short for: `>=0.4.2 <1.0`
> Update phinx version in composer.json

- .travis.yml
- README.md
- src/Command/MarkMigrated.php
- src/ConfigurationTrait.php
- src/MigrationsDispatcher.php
- src/Shell/Task/MigrationSnapshotTask.php
- tests/TestCase/Command/MarkMigratedTest.php
- tests/TestCase/Shell/Task/MigrationSnapshotTaskTest.php
- tests/test_app/config/Migrations/20150416223600_mark_migrated_test.php
When a snapshot is baked, the matching migration should be marked as migrated.
This PR adds a new command "MarkMigrated". This command takes the version number of the migrations to be marked as migrated :
`./bin/cake migrations mark_migrated {version}`
When a snapshot is baked and the file has successfully been written, this command is dispatch with dispatchShell().
If you're on board with the idea behind this change, I'll start digging to find out how to test all that.
I'll also probably need to propagate potential arguments used with bake (such as connection or plugin) to the dispatchShell() call.
More details on #65
> Marking snapshot migrated after bake

- src/Template/Bake/config/skeleton.ctp
As reported in #74, if you bake a migration with an index creation, the index column name in enclosed in double quotes, which it should not.
Currently rendering :
```php
// [...]
$table->addIndex(["
'status_id',
"], [
'name' => 'status_id',
'unique' => false,
]);
// [...]
```
With this fix, renders as :
```php
$table->addIndex([
'status_id',
], [
'name' => 'status_id',
'unique' => false,
]);
```
Should solve #74
> Indexes columns stringification should not be enclosed in double quotes when baking

- src/Command/MarkMigrated.php
- tests/TestCase/Command/MarkMigratedTest.php
Before marking a migration as migrated when ``mark_migrated`` is called, it would be nice to check if the migration has not already been migrated (or marked as such).
This does not really change anything and does not fix a bug :
- phinx already deals with the case where a migration is marked migrated multiple times (when a migration is rollbacked, it just deletes everything with the version number). 
- when the ``status`` command is called, it uses the files in the migration path to build the migrations list.
But I figured it would be nicer to have this as it would help to keep a clean ``phinxlog`` table.
I also changed the concatenations in the outputed messages by ``sprintf()`` calls.
> Checks if a migration has already been marked as migrated before marking it migrated

- src/Template/Bake/config/snapshot.ctp
- src/View/Helper/MigrationHelper.php
- tests/Fixture/CategoriesFixture.php
- tests/Fixture/ProductsFixture.php
- tests/TestCase/Shell/Task/MigrationSnapshotTaskTest.php
- tests/comparisons/Migration/testNotEmptySnapshot.php
When baking a snapshot, indexes and constraints where not baked and thus, lost.
This PR aims to correct that.
The only thing I could not do was to support composite foreign keys as Cake doesn't seem to support them. Am I correct ? From what I gathered, when a table has a multi-columns foreign key defined and is reflected, the last column within the list is the one that persists.
Should I create an issue in the main repo with what I used to test and conclude this ?
More details on #80
> Indexes and constraints are now baked with the snapshot

- .travis.yml
Builds with HHVM nightly are no longer supported by Travis.
See https://travis-ci.org/cakephp/migrations/jobs/63081340
> HHVM nightly is no longer supported by Travis

- src/Shell/MigrationsShell.php
The problem described in #82 occurred because the MigrationsShell ``getOptionParser()`` method did not define the format option.
The --format option should now work correctly :
``bin/cake migrations status`` =>
```bash
Status  Migration ID    Migration Name 
-----------------------------------------
up  20150522230848  AlterUsers
```
---------------------
``bin/cake migrations status -f json``
```bash
using format json
Status  Migration ID    Migration Name 
-----------------------------------------
up  20150522230848  AlterUsers
[{"migration_status":"up","migration_id":"20150522230848","migration_name":"AlterUsers"}]
```
Resolves #82
> The "--format" option should be define in the MigrationsShell options parser

- src/Shell/MigrationsShell.php
- src/Shell/Task/MigrationSnapshotTask.php
- tests/TestCase/Shell/Task/MigrationSnapshotTaskTest.php
After a snapshot was baked, the ``connection`` and the ``plugin`` options should be propagated to the ``mark_migrated`` dispatched Shell.
Not doing so resulted in the ``mark_migrated`` call to be executed with the default connection which was unexpected and caused problems.
I know the tests and the mark_migrated shell dispatching seems weird but I actually can put anything in place of the ``$dispatchCommand`` and it would work. What matters is the content of the ``$_SERVER['argv']`` variable (if anyone knows why and would care to explain, I'll be glad).
But I still need to build a correct string for the tests.
Should fix #88
> Fix baking snapshots

- README.md
This adds a note on the README about collations.
It is currently only possible to have a different collation than the database default one on table creation and only for MySQL and SqlServer.
I thought this should be written somewhere.
Refs #63
> Add a note on the README about collations

- tests/Fixture/CategoriesFixture.php
- tests/Fixture/CompositePkFixture.php
- tests/Fixture/ProductsFixture.php
- tests/Fixture/SpecialPkFixture.php
- tests/Fixture/SpecialTagsFixture.php
- tests/Fixture/UsersFixture.php
The links to the testing part of the document points to the 2.X documentation.
This points them to the 3.X documentation.
> Corrects the "Tests" links in the Fixtures docblocks

- src/Template/Bake/config/snapshot.ctp
- tests/Fixture/OrdersFixture.php
- tests/TestCase/Shell/Task/MigrationSnapshotTaskTest.php
- tests/bootstrap.php
- tests/comparisons/Migration/testCompositeConstraintsSnapshot.php
- tests/comparisons/Migration/testNotEmptySnapshot.php
Since composite foreign keys constraints support was added in CakePHP schema reflection, baked migrations should support them as well.
> Add composite foreign key constraints generation when baking a snapshot

- src/Shell/MigrationsShell.php
Make the runCommand method compatible with the parent method https://github.com/cakephp/cakephp/blob/3.1/src/Console/Shell.php#L402
Not sure if it can be directly merged to master, since this is a problem of Cake 3.1.
> Make runCommand method compatible with parent

- src/ConfigurationTrait.php
I have to use a unix-socket in my local setup to be able to connect to the database. This socket-setting was not passed on to phinx, which led to following error:
`[InvalidArgumentException]`
`There was a problem connecting to the database: SQLSTATE[HY000] [1045] Access denied for user 'username'@'localhost' (using password: YES)`
This patch passes the socket info on to phinx, thus enabling migrations on systems that use sockets.
> if a unix_socket is set, it will now be passed on in the config-array

- src/Shell/Task/MigrationSnapshotTask.php
- src/Template/Bake/config/snapshot.ctp
- tests/Fixture/ArticlesFixture.php
- tests/Fixture/ProductsFixture.php
- tests/TestCase/Shell/Task/MigrationSnapshotTaskTest.php
- tests/comparisons/Migration/testCompositeConstraintsSnapshot.php
- tests/comparisons/Migration/testNotEmptySnapshot.php
When tables are fetched from the database, they need to be ordered following foreign keys constraints dependencies to avoid table creation referencing tables that do not exist yet.
When dropping tables, their order needs to be reversed to avoid constraints failure.
I added a new ``ArticlesFixture`` to test the behaviour which has a constraint on ``CategoriesFixture``. Since it is alphabetically before and the ``categories`` table should be created before the ``articles`` table is, it allows to check the good ordering.
I also fixed a docblock along the way
Refs #100
> Tables need to be ordered to respect foreign keys constraints dependencies

- src/View/Helper/MigrationHelper.php
- tests/Fixture/CategoriesFixture.php
- tests/Fixture/CompositePkFixture.php
- tests/Fixture/ProductsFixture.php
- tests/Fixture/SpecialPkFixture.php
- tests/TestCase/Shell/Task/MigrationSnapshotTaskTest.php
- tests/comparisons/Migration/testCompositeConstraintsSnapshot.php
- tests/comparisons/Migration/testNotEmptySnapshot.php
Currently, the Postgres build is triggering a fatal error when creating the Fixtures for the tests.
This PR aims to prevents it.
Even if the Postgres build has errors around integer length when reflected by Cake Schema system (see https://github.com/cakephp/cakephp/issues/5901 & https://github.com/cakephp/migrations/commit/a57b25e5e3ac6d144441f4ebba0c0d4f80c46275), having failing assertions at least allow us to see if some additions does not trigger fixable mistakes with Postgres.
> Prevent the Postgres build from triggering a fatal error

- .travis.yml
- Add PHP7 tests
- Make PHPCS runs on PHP7 (it should be faster)
- Allow coveralls.io to fail
> Update the Travis build matrix with PHP7

- src/Migrations.php
- tests/TestCase/MigrationsTest.php
The Manager object Phinx used stores the migrations whenever some are found through a command.
The Migrations class erases them from the Manager object when a method is used to prevent wrong migrations to be returned.
This is done only if the migrations path between two calls are different.
This bug went unseen because in the tests, a dummy input is generated and passed to a Migrations object in order to get the PDO instance and share it with other objects (needed because of SQLite and the memory connection). The migrations were then ran against this Migrations object that already had a migrations path defined (because its manager was instanciated already with the dummy input), causing the method to raise an exception.
The tests now run migrations with a new object to make sure the bug …
> The check for different migrations paths should only be done if a migrations path was already defined

- src/CakeManager.php
- src/Command/Migrate.php
- src/Command/Rollback.php
- src/Command/Status.php
- src/Migrations.php
- src/Shell/MigrationsShell.php
- src/View/Helper/MigrationHelper.php
- tests/TestCase/MigrationsTest.php
The date option was added in Phinx 0.4.5 release and allow migrations to be migrated or rollbacked by specifying a date rather than targeting a specific migration
I also updated the classes to use the ``EventDispatcherTrait`` rather than the deprecated ``EventManagerTrait``.
I also fixed some docblocks.
Closes #117
> Update the Migrate and Rollback commands with the new date option.

- src/CakeManager.php
- src/Migrations.php
- tests/TestCase/Command/MarkMigratedTest.php
- tests/TestCase/MigrationsTest.php
This is a follow up PR for #118.
- I rewrote the way the Migrations class chooses which method of the Manager to run.
- I rewrote the ``CakeManager::rollbackToDateTime()`` method to cover a case that was not (if you want to rollback to a date that is after the last migrations date, nothing should be rollbacked).
The changes of the MarkMigratedTest are not linked to #118 but I changed a few things.
> Follow up on #118

- src/ConfigurationTrait.php
- tests/TestCase/ConfigurationTraitTest.php
- tests/TestCase/Shell/Task/MigrationSnapshotTaskTest.php
- tests/TestCase/Shell/Task/MigrationTaskTest.php
This PR allows establishing the connection to a mysql database with phinx using SSL if parameters are defined in the CakePHP Connection object.
Refs to issue #99 and PR #103
> Add support for establishing a connection to MySQL using SSL

- composer.json
- src/CakeAdapter.php
- src/Migrations.php
- src/Table.php
- src/Template/Bake/config/snapshot.ctp
- tests/TestCase/MigrationsTest.php
- tests/TestCase/Shell/Task/MigrationSnapshotTaskTest.php
- tests/comparisons/Migration/pgsql/test_auto_id_disabled_snapshot_pgsql.php
- tests/comparisons/Migration/pgsql/test_composite_constraints_snapshot_pgsql.php
- tests/comparisons/Migration/pgsql/test_not_empty_snapshot_pgsql.php
- tests/comparisons/Migration/sqlite/test_auto_id_disabled_snapshot_sqlite.php
- tests/comparisons/Migration/sqlite/test_composite_constraints_snapshot_sqlite.php
- tests/comparisons/Migration/sqlite/test_not_empty_snapshot_sqlite.php
- tests/comparisons/Migration/test_auto_id_disabled_snapshot.php
- tests/comparisons/Migration/test_composite_constraints_snapshot.php
- tests/comparisons/Migration/test_not_empty_snapshot.php
**This should not be merged right now**
This phinx release and this PR shed some light on some migrations tests that were not done. Now that they are all running, I spotted a bug in phinx implementation of the mechanism to drop foreign key constraints with SQLite. I submitted a PR on phinx repo : https://github.com/robmorgan/phinx/pull/641
The test suite will be failing for SQLite until the change I will propose will be merged and a new phinx release is 
-----------------------
This phinx release introduced changes in the naming scheme the migration files / the migration classes should follow, breaking the tests.
This commit also removes the ``update()`` call after the ``dropForeignKey()`` calls : it was not necessary.
> Update the tests so they pass again following the release of phinx 0.4.6

- README.md
- src/Command/MarkMigrated.php
- tests/TestCase/Command/MarkMigratedTest.php
- tests/TestCase/MigrationsTest.php
Added a special value ``all`` for the ``version`` argument of the ``mark_migrated`` command.
It allows to mark all migrations found (based on the other arguments) as migrated in one call.
Everything is done in one transaction. If one the marking as migrated operations raises an exception, the entire process is cancelled and the transaction rollbacked.
I went with ``all`` instead of ``*`` because the ``*`` raised a ``TooManyArguments`` exception (I could figured out why though).
And ``all`` is closer to what we have in bake for instance.
The tests will fail because I'm waiting for https://github.com/robmorgan/phinx/pull/641 to be reviewed, tested and merged (to be able to merge #123 after the build passes).
Refs #124
> Allow to migrate all migrations with one "mark_migrated" call

- composer.json
- src/Command/Migrate.php
- src/Command/Rollback.php
- tests/TestCase/Shell/Task/MigrationSnapshotTaskTest.php
Following changes to other projects, min requirement for Cake is now 3.1.
> Bump up the minimum requirement to CakePHP 3.1

- src/Shell/Task/MigrationTask.php
- tests/TestCase/Shell/Task/MigrationTaskTest.php
Hi guys,
I ran into a very specific case where the MigrationTask#detectAction is returning the wrong table name:
`bin/cake bake migration AddSomeFieldToTodos`
It gets the table name as being `dos` instead of `todos`. It seems to occur for every table that starts with `to`.
> fixing MigrationTask#detectAction bug for adding field #133

- src/Shell/MigrationsShell.php
When called from another shell, migrations would exit instead of returning
```
$this->dispatchShell('migrations migrate');
$this->out('this won't be printed in the console');
```
> Prevent phinx from exiting after the migration

- README.md
- src/Util/ColumnParser.php
- tests/TestCase/Shell/Task/MigrationTaskTest.php
- tests/TestCase/Util/ColumnParserTest.php
- tests/comparisons/Migration/testCreateFieldLength.php
This allows to specify the field length when baking a new migration file by allowing the ``fieldType`` syntax to accept a number written within brackets :
``bin/cake bake migrations create_users username:string[128]``
I went with brackets because parenthesis cause the shell call to fail.
I did not add any test to control the length specified other than the one that were already done because phinx does it with the adapters and default sizes based on the field type.
Refs to #128
> Add the ability to specify the field length to the bake command

- README.md
- src/Command/MarkMigrated.php
- tests/TestCase/Command/MarkMigratedTest.php
Finally now it seems right!!
Sorry for the mess.
Recommenting:
The way it was implemented it should be used like:
`bin/cake migrations mark_migrated VERSION --skip-to` will mark all migrations from beginning until VERSION
`bin/cake migrations mark_migrated VERSION --up-to` will mark all migrations from beginning to VERSION (including it)
@HavokInspiration does it seem good?
Right now there are some duplicated logic (the migrations are being marked as migrated inside execute($input, $output) and markVersionsAsMigrated($path, $versions)). I can refactor it if you intend to merge :)
> Skip to and up to options feature

- src/Command/Create.php
- src/Command/MarkMigrated.php
- src/Command/Migrate.php
- src/Command/Rollback.php
- src/Command/Status.php
- src/Shell/MigrationsShell.php
- src/Shell/Task/MigrationSnapshotTask.php
- tests/TestCase/Command/MarkMigratedTest.php
- tests/TestCase/Shell/Task/MigrationSnapshotTaskTest.php
This PR has two goals :
It's a follow up to #137, I forgot a key point when adding options : they have to be added to the MigrationsShell class otherwise the shell call can't execute.
I also updated the dispatched command that was issued after a snapshot was baked so it doesn't mark all migrations as migrated.
----------
Options mode should use a ``InputOption`` constant. Flags (bool values) use a ``InputOption::VALUE_NONE`` mode and options which are expecting a value should use ``InputOption;;VALUE_REQUIRED``
Refs http://symfony.com/doc/current/components/console/introduction.html#using-command-options
> Follow up to #137

- src/Shell/Task/MigrationTask.php
- tests/TestCase/Shell/Task/MigrationTaskTest.php
> fix issue with field name starting with a delimiter

- src/CakeAdapter.php
ref robmorgan/phinx#580 to avoid again a new plugin failure on the next release of phinx.
> implement the new ``hasIndexByName()``

- src/ConfigurationTrait.php
ConfigurationTrait  does not take the correct values in app postgresql schema settings.
> ConfigurationTrait postgresql schema config bug fixed #150

- src/Shell/Task/MigrationSnapshotTask.php
> Remove the i18n table from the tables to skipped when baking a snapshot

- src/Shell/Task/MigrationSnapshotTask.php
Fix to create snapshot for all tables from plugin when using --plugin and --require-table options. Now only creates snapshot for only one table from plugin
> Fix to create snapshot for all tables from plugin

- src/CakeAdapter.php
- src/CakeManager.php
- src/Shell/Task/MigrationSnapshotTask.php
- src/Shell/Task/MigrationTask.php
- src/Shell/Task/SimpleMigrationTask.php
- src/Template/Bake/config/skeleton.ctp
- src/Util/ColumnParser.php
- src/View/Helper/MigrationHelper.php
- tests/TestCase/Shell/Task/MigrationTaskTest.php
Cleanup as follow up on https://github.com/cakephp/migrations/pull/161
> CS Cleanup

- README.md
- src/Table.php
Clear the TableRegistry after an update call in order to prevent issues with the Schema stored in Table objects that could be out of sync after a column rename or deletion.
This however implies that every Table objects are needed to be recreated in order for this to have an effect.
Refs #157
> Clear the TableRegistry after an update call

- src/Shell/MigrationsShell.php
- src/Shell/Task/CommandTask.php
- src/Shell/Task/CreateTask.php
- src/Shell/Task/MarkMigratedTask.php
- src/Shell/Task/MigrateTask.php
- src/Shell/Task/RollbackTask.php
- src/Shell/Task/StatusTask.php
- tests/TestCase/Shell/Task/CommandTaskTest.php
- tests/TestCase/Shell/TestCompletionStringOutput.php
In line with other improvements made to autocompletion feature with the CakePHP shell, this PR aims to introducte autocompletion to the Migrations Shell (and fix #145).
To do so, I implemented a Cake Task for each of the subcommands the migrations shell supports. This tricks the completion shell to suggest the subcommands and options specific to subcommands.
However, the options registration in the MigrationsShell still needs to be there otherwise the shell calls will trigger errors of undefined options.
**Note : build will fail** as long as the changes made to the CompletionShells will not be tagged with a new CakePHP release. So we should wait before merging.
The only downside I find to this is that it adds a few classes "just" for that. Might be too much but it is the only "quick and …
> Introduce autocompletion to the Migrations Shell

- README.md
- composer.json
In order to fix #167 and prevent users using the CakePHP 3.0.X release cycle from running into trouble when doing a ``composer update``, we should release a last compatible version for this cycle. Currently, 1.3.1 leads to problems raised in #167.
So I restored the dependency schema we had before pinning to ``dev-master`` for ``robmorgan/phinx`` but I changed the max dependency to ``0.5.0`` (I suspect there will be no more ``0.4.x`` release anymore).
If you think we should play "safe", we can edit to force it to 0.4.6 where we know it should properly work (I won't be able to edit it for a couple of days, but the diff branch is on the cakephp repo, so feel free to edit it at will).
I also updated the README with some important notes.
This should prevent any future problems with users using …
> [1.3.X] Update phinx dependency to a more suitable version

- src/Template/Bake/config/snapshot.ctp
- src/View/Helper/MigrationHelper.php
- tests/TestCase/View/Helper/MigrationHelperTest.php
Basically adds precision to the wantedOptions array in the snapshot template, then adds sum array element juggling to make sure the options (if set) line up with the Phinx equivalents
Also changes the Migration helper `value` method to return a float rather than an integer for numerics values.
This fixes my particular use case, so I thought I'd share it.
Fixes #168
> Fix snapshot decimals handling

- README.md
- src/Shell/Task/MigrationSnapshotTask.php
- tests/TestCase/Shell/Task/MigrationSnapshotTaskTest.php
- tests/comparisons/Migration/pgsql/test_plugin_blog_pgsql.php
- tests/comparisons/Migration/sqlite/test_plugin_blog_sqlite.php
- tests/comparisons/Migration/test_plugin_blog.php
- tests/test_app/Plugin/Blog/src/Model/Entity/Article.php
- tests/test_app/Plugin/Blog/src/Model/Table/ArticlesTable.php
When baking a snapshot for a plugin, the tables that will be picked to be exported are now only the ones that have table classes defined in the plugin's ``src``. Basically, if you bake a snapshot for a plugin, it will be as if you used the ``--require-table`` flag.
It is the only way I found to prevent application tables to be exported as well when baking for a plugin.
Defining Table classes in the plugin is now **mandatory** to bake a snapshot for a plugin.
Refs #172
> Fix baking a plugin snapshot

- src/Shell/Task/MigrationSnapshotTask.php
- tests/test_app/Plugin/Blog/src/Model/Entity/Dog.php
- tests/test_app/Plugin/Blog/src/Model/Table/DogsTable.php
The check was made with the wrong array leading to potentially non-existent table to be added in a snapshot, leading to errors during baking
> Fix the table names filtering when require-table is set to true

- src/Shell/Task/SeedTask.php
- src/Template/Bake/Seed/seed.ctp
This is part one of the necessary work to add support for phinx seeds. Our next step is to add support to the migrations runners to actually apply seeds to a database.
Opening PR to continue discussion based on running code :)
Refs #19.
> Add initial support for generating seed files

- src/CakeManager.php
- src/ConfigurationTrait.php
- src/Migrations.php
- tests/TestCase/Command/SeedTest.php
- tests/TestCase/MigrationsTest.php
- tests/test_app/config/AltSeeds/AnotherNumbersSeed.php
- tests/test_app/config/AltSeeds/NumbersAltSeed.php
This gives the ability to run seed from a non-shell context, using the ``Migrations\Migrations`` class.
Follow up to #179 and #181
> Update the Migrations class to support the seeding feature

- src/CakeAdapter.php
- src/CakeManager.php
- src/Command/MarkMigrated.php
- src/Migrations.php
- tests/TestCase/MigrationsTest.php
This allows the ``\Migrations\Migrations::markMigrated()`` to work as the command now works since the changes introducted in #137 
I had to swap methods from the ``\Migrations\Command\MarkMigrated`` class to the Manager in order to get the correct informations to adapt the ``\Migrations\Migrations::markMigrated()`` method.
This also fixed tests that were passing but for the wrong reasons. An exception was indeed thrown but too early.
The part where the PDO error mode is now set is because Phinx does not set it and for some reasons that still eludes me, the PDO Sqlite driver was not throwing exception when queries could not be executed or prepared. Now it does.
For instance, before that, you could set a migrations with a ``dropTable()`` to a table that does not exist and SQLite would not …
> Migrations `markMigrated()` update (non-shell)

- src/Template/Bake/config/snapshot.ctp
- tests/Fixture/ArticlesFixture.php
- tests/comparisons/Migration/pgsql/test_auto_id_disabled_snapshot_pgsql.php
- tests/comparisons/Migration/pgsql/test_not_empty_snapshot_pgsql.php
- tests/comparisons/Migration/pgsql/test_plugin_blog_pgsql.php
- tests/comparisons/Migration/sqlite/test_auto_id_disabled_snapshot_sqlite.php
- tests/comparisons/Migration/sqlite/test_not_empty_snapshot_sqlite.php
- tests/comparisons/Migration/sqlite/test_plugin_blog_sqlite.php
- tests/comparisons/Migration/test_auto_id_disabled_snapshot.php
- tests/comparisons/Migration/test_not_empty_snapshot.php
- tests/comparisons/Migration/test_plugin_blog.php
If you had indexes (not unique) defined in your table schema not linked to a FK, those indexes were not added to the snapshot.
> Fix the way indexes are added when baking a snapshot

- src/Template/Bake/config/snapshot.ctp
- src/View/Helper/MigrationHelper.php
- tests/Fixture/ArticlesFixture.php
- tests/TestCase/Shell/Task/MigrationSnapshotTaskTest.php
- tests/comparisons/Migration/pgsql/test_auto_id_disabled_snapshot_pgsql.php
- tests/comparisons/Migration/pgsql/test_not_empty_snapshot_pgsql.php
- tests/comparisons/Migration/pgsql/test_plugin_blog_pgsql.php
- tests/comparisons/Migration/sqlite/test_auto_id_disabled_snapshot_sqlite.php
- tests/comparisons/Migration/sqlite/test_not_empty_snapshot_sqlite.php
- tests/comparisons/Migration/sqlite/test_plugin_blog_sqlite.php
- tests/comparisons/Migration/test_auto_id_disabled_snapshot.php
- tests/comparisons/Migration/test_not_empty_snapshot.php
- tests/comparisons/Migration/test_plugin_blog.php
- tests/test_app/Plugin/TestBlog/src/Model/Table/PartsTable.php
This change will not have any effect on Postgres, which does not support signed integer.
Support for SQLite is limited to non-primary keys integers, as SQLite does not support integer unsigned primary keys.
MySQL support unsigned for both integer primary keys and simple integer.
This explains the differences between the comparisons files for each db vendors.
Refs #197
> Include the "unsigned" attribute in snapshot

- composer.json
This should prevent errors when a new version of phinx is released (which happens every single time).
This way we ensure the integrity of the plugin and can bump up the version of the dependency when we implemented what's new in phinx.
When this will be merged, a new release should be made immediately.
Refs #202
> Lock the phinx dependency version

- src/CakeAdapter.php
- tests/ExampleCommand.php
- tests/TestCase/ConfigurationTraitTest.php
If the Schema metadata are generated and put in the cache and a column is added to a table, when doing a data insertion or update, it can results in error because the new column is not in the schema (because metadata are fetched from the cache).
This change completely disables the cache metadata feature.
Refs #199
> Disable table metadata caching mechanism

- composer.json
- src/CakeAdapter.php
> Phinx 0.5.2

- src/Template/Bake/config/snapshot.ctp
- tests/Fixture/ArticlesFixture.php
- tests/comparisons/Migration/pgsql/test_auto_id_disabled_snapshot_pgsql.php
- tests/comparisons/Migration/pgsql/test_not_empty_snapshot_pgsql.php
- tests/comparisons/Migration/pgsql/test_plugin_blog_pgsql.php
- tests/comparisons/Migration/sqlite/test_auto_id_disabled_snapshot_sqlite.php
- tests/comparisons/Migration/sqlite/test_not_empty_snapshot_sqlite.php
- tests/comparisons/Migration/sqlite/test_plugin_blog_sqlite.php
- tests/comparisons/Migration/test_auto_id_disabled_snapshot.php
- tests/comparisons/Migration/test_not_empty_snapshot.php
- tests/comparisons/Migration/test_plugin_blog.php
Postgres needs the default value for boolean field type to be a real boolean value and not 0 or 1.
Refs #207
> Improve support for boolean type in baked snapshot

- .travis.yml
- src/CakeManager.php
- src/Command/Status.php
- src/Shell/Task/MigrationSnapshotTask.php
- src/Template/Bake/config/snapshot.ctp
- tests/Fixture/ProductsFixture.php
- tests/TestCase/Command/StatusTest.php
- tests/TestCase/MigrationsTest.php
- tests/TestCase/Shell/Task/MigrationSnapshotTaskTest.php
- tests/comparisons/Migration/pgsql/test_auto_id_disabled_snapshot_pgsql.php
- tests/comparisons/Migration/sqlite/test_auto_id_disabled_snapshot_sqlite.php
- tests/comparisons/Migration/sqlite/test_not_empty_snapshot_sqlite.php
- tests/comparisons/Migration/test_auto_id_disabled_snapshot.php
- tests/comparisons/Migration/test_auto_id_disabled_snapshot56.php
- tests/comparisons/Migration/test_not_empty_snapshot.php
- tests/comparisons/Migration/test_not_empty_snapshot56.php
- tests/comparisons/Migration/test_plugin_blog56.php
Add support for the new output of the ``status`` command. Basically, the phinxlog now stores the name of the migrations. When missing from the filesystem but outputted because we request the history, the name can now be displayed.
See https://github.com/robmorgan/phinx/pull/744 for more details.
------
When baking a snapshot, fulltext indexes are exported correctly. 
:warning: This is only supported for MySQL :warning: 
However, fulltext indexes for MySQL are only available for InnoDB tables starting from 5.6. This implied to add a new build specifically targeting MySQL 5.6 since Travis runs 5.5 by default (which explains the travis-ninja skills that I had to use to achieve this).
This also means that we have new files (ending by ``56``) to test against when we are testing with the build …
> Add support for phinx 0.5.2 new features

- tests/TestCase/Command/MarkMigratedTest.php
- tests/TestCase/Shell/Task/CommandTaskTest.php
Due to https://github.com/cakephp/cakephp/pull/8635, the output of options are different.
I made the tests skip on 5.4 because that version of the core where the option was implemented is not supported in 5.4.
And even if it is used with 5.4, it should not be that big of a deal breaker given the nature of the change.
Will merge this as soon as possible in order to take care of pending PR.
> Fix expected output of some tests due to a change in CakePHP Core

- src/Migrations.php
A small change to ensure that cached environments are reset when the migration config is changed. Not doing this resulted in weird issues where it would read from the wrong plugin phinxlog. This only occurred when you used a single `Migration()` instance to check the status for multiple plugins
> Reset cached environments when manager config is changed

- src/View/Helper/MigrationHelper.php
Extending `MigrationHelper` class i found there is a "cached" version of each table schema using `schema($table)`: that is good for performance to avoid multiple call to db for same infos, also if you want to extend class behavior about table handling you only have to override one method.
> Use cached version of table schema

- tests/TestCase/View/Helper/MigrationHelperTest.php
- tests/comparisons/Diff/the_diff_pgsql.php
- Changes the way ``default null`` for SQLite is handled for build >= 5.5 (due to the recent change in the core regarding this). The build for 5.4 is still expecting the old way of doing this.
- Fix a bake comparison file for the diff baking feature for Postgres
> Fix expected results from tests

- src/Shell/Task/MigrationDiffTask.php
- src/Shell/Task/MigrationSnapshotTask.php
- src/Shell/Task/SimpleMigrationTask.php
Reverts #222 
Issue #226 happened because the argument added in the option parser makes the "simple" migration baking command ask for only one argument (the name). But since the command allows a user to input multiple columns definitions, the shell raises an error because there are too many arguments.
And since it is not possible to define an argument for "multiple space separated values", #222 has to be reverted.
However sub-classes of the ``SimpleMigrationTask`` can have the ``addArgument`` call since they do not need more than the name of the migration to bake.
> Revert #222 migrationtask argument

- composer.json
- src/Shell/Task/SnapshotTrait.php
- src/Template/Bake/config/snapshot.ctp
- tests/TestCase/Command/DumpTest.php
- tests/TestCase/Shell/Task/MigrationDiffTaskTest.php
- tests/bootstrap.php
- tests/comparisons/Diff/simple/the_diff_simple_pgsql.php
- tests/test_app/App/Model/Table/LettersTable.php
- tests/test_app/App/Model/Table/NumbersTable.php
- tests/test_app/App/Model/Table/SomeAbstractTable.php
When fetching and resolving tables names to add into a baked migration file or a dump file, the shell loads Table classes to use the ``table()`` method to get the real names of the tables.
The problem is that it tries to instanciate any Table classes, including potential abstract class.
This fixes it by using the ``ReflectionClass``.
I also used this PR to add minor fixes and do a bit of cleanup :
- a fix in the Postgres build
- a fix regarding a notice that could appear when baking a snapshot in specific conditions
Refs #229
> Do not try to instanciate non-instanciable classes when resolving tables to bake

- src/Command/Dump.php
- src/Shell/MigrationsShell.php
> Failing calls to the Shell now return a proper exit code

- .travis.yml
- src/AbstractSeed.php
- src/CakeManager.php
- src/Command/Seed.php
- src/Migrations.php
- src/MigrationsDispatcher.php
- src/Shell/MigrationsShell.php
- src/Template/Bake/Seed/seed.ctp
- tests/TestCase/Command/DumpTest.php
- tests/TestCase/Command/MarkMigratedTest.php
- tests/TestCase/Command/SeedTest.php
- tests/TestCase/Command/StatusTest.php
- tests/TestCase/ConfigurationTraitTest.php
- tests/TestCase/MigrationsTest.php
- tests/TestCase/Shell/Task/CommandTaskTest.php
- tests/TestCase/Shell/Task/MigrationDiffTaskTest.php
- tests/TestCase/Shell/Task/MigrationSnapshotTaskTest.php
- tests/TestCase/Shell/Task/MigrationTaskTest.php
- tests/TestCase/Shell/Task/SeedTaskTest.php
- tests/bootstrap.php
- tests/comparisons/Seeds/testBasicBaking.php
- tests/test_app/Plugin/TestBlog/config/CallSeeds/PluginLettersSeed.php
- tests/test_app/Plugin/TestBlog/config/CallSeeds/PluginSubLettersSeed.php
- tests/test_app/Plugin/TestBlog/src/Model/Table/CategoriesTable.php
- tests/test_app/config/CallSeeds/DatabaseSeed.php
- tests/test_app/config/CallSeeds/LettersSeed.php
- tests/test_app/config/CallSeeds/NumbersCallSeed.php
Usually when seeding, the order in which to insert the data must be respected to not encounter constraints violations.
Since Seeders are executed in the alphabetical order, there is currently no way to have one CLI call to do this in a clean way. This PR aims to fix this.
A new ``AbstractSeed`` class has been created which implements a ``call()`` method. This methods expects the name of the Seeder to call. The plugin dot syntax can be used to call seeders from a plugin.
Nested ``call()`` calls are also supported (a called Seeder can call other Seeders, because inception and everything).
I fixed all the ``getMock()`` calls in the tests as well.
Refs #212
> Allows a Seeder to call other Seeders

- src/ConfigurationTrait.php
- src/Shell/Task/SnapshotTrait.php
- tests/test_app/App/Model/Table/NumbersTable.php
This PR aims to fix #239 
It sets the connection name to the commands (really in the ConfigurationTrait) when the command is bootstrapped.
This is kind of a special case for the dump command which uses methods normally reserved to the Bake tasks.
It also fixes a problem with tables name filtering when the table is set with a schema name (``$this->table('schema.table')``) in Table classes. Tables name set this way are removed from the tables to be dumped / baked if there is a mismatch between the schema of the connection passed and the one from the table.
> Sets the connection name to the commands

- src/Util/ColumnParser.php
- tests/TestCase/Util/ColumnParserTest.php
This patch provides the ability to specify that a column is nullable in a migration from the CakePHP bake command line by adding a question mark as a suffix to the column data type.
Example:
`bin/cake bake migration CreatePerson name:string description:string? age:integer?`
The patch applies to the ColumnParser class in src/Util/ColumnParser.php file and the diff can be found at:
https://github.com/nitincoded/migrations/commit/bd453eee3817a6c55d1c4f56c68088041fff84b3
A test was also added to the PHP Unit test in the ColumnParserTest class.
> Add support for specifying a nullable field #203

- src/Command/Dump.php
The ``dump`` command should not set ``require-table`` to true when fetching the tables to add to the dump because it can lead to unexpected results as reported in #232 and #244.
It turned out the issue experienced by @ypnos-web and @dereuromark are because of this option.
@lorenzo As specified in #232, it should be known that tables from plugins will also be added to the dump when migrating or rolling back a set of migrations (basically, the system will now add every tables it finds in the dump), potentially creating a situations where tables from plugin will be added in diffs.
Maybe there could be an option in the migration diff command to exclude tables :
- by specifying a list of table names
- by specifying a plugin name. When used it will fetch all ORM table classes in the said plugin …
> Dump command and require-table

- src/MigrationsDispatcher.php
This is the change I propose to fix the code swallowing info on exceptions thrown by migrations.
> Don't catch exceptions in migrations (fixes #258)

- src/Shell/Task/MigrationDiffTask.php
- tests/TestCase/Shell/Task/MigrationDiffTaskTest.php
When generating a snapshot all "*phinxlog" tables are skipped. However when baking a diff only "phinxlog" table is skipped, which I guess is wrong.
> Skip phinxlog tables in diff

- src/Shell/Task/MigrationDiffTask.php
This should fix the build which is currently failing.
It failed because of https://github.com/cakephp/cakephp/pull/8978 which added a new property (column collation) in columns reflection which is not supported by phinx (for the version the plugin is pinned to at least).
For the time being, I'll just remove the property. Maybe when we bump up phinx supported version, it might go away, in case per-column collation is supported.
> Fix MySQL build

- src/CakeAdapter.php
- tests/TestCase/Shell/Task/MigrationDiffTaskTest.php
This is a fix for the Postgres build. It is still failling about something that I never had the time to check out and try to fix, but now the build does not error out anymore. The current failure have been here for quite some time now and does not prevent the plugin to work.
However, what has been implemented here might fix #254. I'll wait for this to be merged to reach out to the user that reported the issue to check if this is fixing the issue he is having.
> Fix (partially) the Postgres Build

- src/View/Helper/MigrationHelper.php
- tests/Fixture/ArticlesFixture.php
- tests/TestCase/View/Helper/MigrationHelperTest.php
- tests/comparisons/Migration/pgsql/test_auto_id_disabled_snapshot_pgsql.php
- tests/comparisons/Migration/pgsql/test_not_empty_snapshot_pgsql.php
- tests/comparisons/Migration/pgsql/test_plugin_blog_pgsql.php
- tests/comparisons/Migration/sqlite/test_auto_id_disabled_snapshot_sqlite.php
- tests/comparisons/Migration/sqlite/test_not_empty_snapshot_sqlite.php
- tests/comparisons/Migration/sqlite/test_plugin_blog_sqlite.php
- tests/comparisons/Migration/test_auto_id_disabled_snapshot.php
- tests/comparisons/Migration/test_auto_id_disabled_snapshot56.php
- tests/comparisons/Migration/test_not_empty_snapshot.php
- tests/comparisons/Migration/test_not_empty_snapshot56.php
- tests/comparisons/Migration/test_plugin_blog.php
- tests/comparisons/Migration/test_plugin_blog56.php
This is proposition to fix issue #266.
By forcing `default` values to be treated as strings, we should prevent localized float typecast to build erroring migration files.
> Change type of `default` values

- src/Shell/Task/MigrationTask.php
- tests/TestCase/Shell/Task/MigrationTaskTest.php
When the name of migrations provided when calling a `bake` command follows the "action" convention, the computed table name should not be pluralized and should follow the input of the user
> Stop pluralizing table name when baking migrations

- src/Template/Bake/Element/add-foreign-keys.ctp
- src/View/Helper/MigrationHelper.php
- tests/Fixture/ArticlesFixture.php
- tests/comparisons/Diff/the_diff.php
- tests/comparisons/Diff/the_diff_mysql.php
- tests/comparisons/Diff/the_diff_pgsql.php
- tests/comparisons/Migration/pgsql/test_auto_id_disabled_snapshot_pgsql.php
- tests/comparisons/Migration/pgsql/test_not_empty_snapshot_pgsql.php
- tests/comparisons/Migration/pgsql/test_plugin_blog_pgsql.php
- tests/comparisons/Migration/sqlite/test_auto_id_disabled_snapshot_sqlite.php
- tests/comparisons/Migration/sqlite/test_not_empty_snapshot_sqlite.php
- tests/comparisons/Migration/sqlite/test_plugin_blog_sqlite.php
- tests/comparisons/Migration/test_auto_id_disabled_snapshot.php
- tests/comparisons/Migration/test_auto_id_disabled_snapshot56.php
- tests/comparisons/Migration/test_not_empty_snapshot.php
- tests/comparisons/Migration/test_not_empty_snapshot56.php
- tests/comparisons/Migration/test_plugin_blog.php
- tests/comparisons/Migration/test_plugin_blog56.php
Baking diff now correctly writes contraints action names.
While at it, I made sure snapshots already do it properly.
Refs #273
> Correctly handle constraints action names on diff

- composer.json
- src/CakeAdapter.php
- src/CakeManager.php
- src/Command/Rollback.php
- src/Command/Seed.php
- src/ConfigurationTrait.php
- src/Migrations.php
- src/Shell/MigrationsShell.php
- tests/TestCase/Command/DumpTest.php
- tests/TestCase/Command/MarkMigratedTest.php
- tests/TestCase/Command/SeedTest.php
- tests/TestCase/Command/StatusTest.php
I upgraded with the idea in mind of having our test suite passing.
There is no guarantee that all new Phinx features between 0.5.3 (the current version pinned) and 0.6.5 (the latest) will work out of the box but I'm thinking we can go from there (with the plugin working as expected) and patch things up as we go.
> Upgrade to Phinx 0.6.5

- src/Shell/Task/MigrationDiffTask.php
- tests/comparisons/Diff/the_diff.php
- tests/comparisons/Diff/the_diff_mysql.php
- tests/comparisons/Diff/the_diff_pgsql.php
When baking a diff, the attribute `length` / `limit`, `default` and ` null` are always included in `changeColumn` instructions.
Since when some of these attributes are not here, phinx uses a default value, this could lead to data desynchronization of value from these attributes when rolling back and migrating again.
Refs #274
> When baking a diff, the attribute `length` / `limit`, `default` and ` null` are always included in `changeColumn` instructions.

- src/Command/Seed.php
No need to convert the seed parameter to an array if it is already an array
Refs #297
> No need to convert the seed parameter to an array if it is already an array

- src/View/Helper/MigrationHelper.php
- tests/comparisons/Diff/the_diff.php
- tests/comparisons/Diff/the_diff_mysql.php
- tests/comparisons/Diff/the_diff_pgsql.php
Baking a diff with a `decimal` type column would lead to errors and notice emitted (a `Undefined index: limit`) with invalid properties set in the `decimal` type column.
This makes sure it does not happen anymore.
Note : Postgres build will fail really bad. But since it's allowed to fail this is not a big deal but until then it might clock other errors it can have.
I fixed what was wrong with the `decimal` support in Postgres in https://github.com/cakephp/cakephp/pull/9955.
For Postgres build to start getting better and return its usual errors, we will need to wait for the fix in the core to be included in a stable release.
> Improve support for baking diff including the addition of a column with the `decimal` type

- src/Command/Dump.php
- tests/TestCase/Command/DumpTest.php
When running the `dump` command on an empty database, it should create an empty `dump.lock` file (well, not completely empty, but with the content of a serialized empty array).
Otherwise, when rolling back the last migration, the dump file was left in its current state which does not make much sense.
Refs #294
> An empty database should create an empty dump file

- .travis.yml
- src/CakeAdapter.php
- src/Table.php
- tests/Fixture/CategoriesFixture.php
- tests/Fixture/CompositePkFixture.php
- tests/Fixture/ProductsFixture.php
- tests/TestCase/MigrationsTest.php
- tests/comparisons/Diff/the_diff.php
- tests/comparisons/Diff/the_diff_mysql.php
- tests/comparisons/Diff/the_diff_pgsql.php
- tests/comparisons/Migration/pgsql/test_auto_id_disabled_snapshot_pgsql.php
- tests/comparisons/Migration/pgsql/test_not_empty_snapshot_pgsql.php
- tests/comparisons/Migration/sqlite/test_auto_id_disabled_snapshot_sqlite.php
- tests/comparisons/Migration/sqlite/test_not_empty_snapshot_sqlite.php
- tests/comparisons/Migration/sqlite/test_plugin_blog_sqlite.php
- tests/comparisons/Migration/test_auto_id_disabled_snapshot.php
- tests/comparisons/Migration/test_auto_id_disabled_snapshot56.php
- tests/comparisons/Migration/test_not_empty_snapshot.php
- tests/comparisons/Migration/test_not_empty_snapshot56.php
- tests/comparisons/Migration/test_plugin_blog.php
- tests/comparisons/Migration/test_plugin_blog56.php
- tests/test_app/config/TestsMigrations/20150704160200_create_numbers_table.php
When creating a table, the Table::create() method will apply the database default collation is none is provided in the Table object options.
This only works for MySQL as phinx only support table collation for this database driver.
Refs #278
> Use database default collation when creating a table if none is provided

- src/Shell/Task/SimpleMigrationTask.php
- tests/TestCase/Shell/Task/MigrationTaskTest.php
If you use this command multiple times :
`bin/cake bake migration TestCreate`
It will create the same file with the same class name each time which will, in the end, trigger an exception when migrating.
The problems should be caught early on and this PR implements a mechanism that prevents to create a migration if it already has the same name as another one in the target directory.
> When baking migrations, we should prevent duplicate names

- composer.json
Hi, 
I have removed `cakephp/cakephp` from require and moved to require-dev , this helps to use it as a standalone without installing cakephp framework itself.
Thank you.
> Remove cakephp/cakephp from require. Add orm and cache

- src/Shell/Task/SimpleMigrationTask.php
- tests/TestCase/Shell/Task/MigrationDiffTaskTest.php
- tests/TestCase/Shell/Task/MigrationSnapshotTaskTest.php
- tests/TestCase/Shell/Task/MigrationTaskTest.php
`bin/cake migrations create` generates files with underscored names. I reckon `bin/cake bake migration_diff` should do it same way.
> Undersocre migration diff filename

- src/Shell/Task/SimpleMigrationTask.php
- tests/TestCase/Shell/Task/MigrationDiffTaskTest.php
- tests/TestCase/Shell/Task/MigrationSnapshotTaskTest.php
- tests/TestCase/Shell/Task/MigrationTaskTest.php
Reverts cakephp/migrations#313
As discussed in #313, CamelBack formatted file name have been pushed in the doc for several month.
PR #299 was created to had the same filename format and sync the behavior of the `bake migration` and `migrations create` commands.
It just was not visible because a few PR were merged after the last release.
> Revert "Undersocre migration diff filename"

- src/Util/UtilTrait.php
- tests/PHPStan/bootstrap.phpstan.php
- tests/bootstrap.php
I have a custom config location, but I saw that migration ignores them.
> Use CONFIG constant if defined

- src/Template/Bake/Element/create-tables.ctp
- tests/TestCase/Shell/Task/MigrationSnapshotTaskTest.php
- tests/comparisons/Migration/pgsql/test_auto_id_disabled_snapshot_pgsql.php
- tests/comparisons/Migration/pgsql/test_not_empty_snapshot_pgsql.php
- tests/comparisons/Migration/sqlite/test_auto_id_disabled_snapshot_sqlite.php
- tests/comparisons/Migration/sqlite/test_not_empty_snapshot_sqlite.php
- tests/comparisons/Migration/test_auto_id_disabled_snapshot.php
- tests/comparisons/Migration/test_auto_id_disabled_snapshot56.php
- tests/comparisons/Migration/test_not_empty_snapshot.php
- tests/comparisons/Migration/test_not_empty_snapshot56.php
Fixes #369, fixes #349.
When table has no primary keys, `bin/cake bake migration_snapshot` throws `Undefined offset` notices.
> Fix snapshot creation for tables with no primary keys

- src/ConfigurationTrait.php
This makes Migrations::status() independent of the Migrations plugin being loaded first.
Refs: https://github.com/orca-services/cakephp-heartbeat/issues/18
> Use relative path instead of plugin path

- src/Shell/MigrationsShell.php
The dry-run feature from Phinx wasn't working for migrations. This fixes it.
> Enable dry-run for migrations

- src/Table.php
I noticed that can not use the autoIncrement option with `changeColumn()` method.
I think that it is better to enable the option also in `changeColumn()` method.
> Enable autoIncrement option with changeColumn method

- src/Template/Bake/config/skeleton.ctp
- src/Util/ColumnParser.php
- tests/TestCase/Util/ColumnParserTest.php
Following the discussion on #388 
This PR focuses on enabling the usage of `decimal` .
The idea is to default `longitude` and `latitude` to be infered as `decimal(10,6)` while also enabling use-cases where a user might want to calculate taxes and store amount which has decimal value.
> Enabling decimal through cake bake and infering types latitude and longitude

- .travis.yml
Travis on Ubuntu Xenial needs `services` to be defined for databases.
https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment#1-services-support
Currently Travis jobs fails with
`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)`
and
```
psql: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```
> Fix Travis database config

- composer.json
Since 0.11 was a bad release in terms of semver (should have been 0.10.x), we should especially now try to support asap.
It should be rather easy to include as it was pretty much full BC.
Thx to prefer-lowest in travis we can also be sure the old version still is fine on future patches.
> Allow next major

- src/Command/BaseCommand.php
- src/Command/CacheBuild.php
- src/Command/CacheClear.php
- src/Command/CommandTrait.php
- src/Command/Create.php
- src/Command/Dump.php
- src/Command/MarkMigrated.php
- src/Command/Migrate.php
- src/Command/Rollback.php
- src/Command/Seed.php
- src/Command/Status.php
- src/Shell/MigrationsShell.php
- tests/bootstrap.php
- tests/bootstrap.phpstan.php
This is required for https://github.com/cakephp/phinx/pull/1653 to not throw warnings now.
Also fixed up return types for newer symfony versions and their expections
> 1) Migrations\Test\Command\CacheBuildTest::testExecute
TypeError: Return value of "Migrations\Command\CacheBuild::execute()" must be of the type int, boolean returned.
I can prepare a patch release here.
> Remove version part

- composer.json
- src/Command/Create.php
- src/Command/Migrate.php
- src/Command/Rollback.php
While technically valid, having the aliasing on other use statements
can be quite confusing, and it seems to trip IDE code completion.
> Move trait method aliasing to the "correct" use statement.

- composer.json
- docs/en/index.rst
I didnt want to add it here as classes in this repo, with an optional dependency towards IdeHelper.
Instead, it is now shipped by default in the IdeHelper.
Knowing that it exists will help here then.
See
https://github.com/dereuromark/cakephp-ide-helper/pull/181
> Add IdeHelper suggest

- composer.json
- src/Command/BakeMigrationDiffCommand.php
`fixed` has been removed from TableSchema
Refs: cakephp/cakephp#13843
tests now should be green
before this change , lock file had `fixed` from cake 3
I did not removed it from test lock file
> unset `fixed` from schema list

- src/Command/BakeMigrationDiffCommand.php
cache causes invalid result in migration diff command
should we disable the cache at all?
also there are other places
> disable  cache

- src/View/Helper/MigrationHelper.php
Apparently, the current code can cause
> bin/cake bake migration_diff bla
Exception: Argument 1 passed to Cake\Utility\Inflector::underscore() must be of the type string, null given, called in /var/www/app/api/vendor/cakephp/migrations/src/View/Helper/MigrationHelper.php on line 262
In [/var/www/app/api/vendor/cakephp/cakephp/src/Utility/Inflector.php, line 399]
> Fix type exception.

- src/Table.php
- tests/TestCase/Command/Phinx/DumpTest.php
- tests/TestCase/Command/Phinx/MarkMigratedTest.php
- tests/TestCase/Command/Phinx/SeedTest.php
- tests/TestCase/Command/Phinx/StatusTest.php
- tests/TestCase/MigrationsTest.php
- tests/TestCase/View/Helper/MigrationHelperTest.php
Psalm
> ERROR: DeprecatedClass - src/Table.php:153:9 - Cake\ORM\TableRegistry is marked deprecated (see https://psalm.dev/098)
TableRegistry::getTableLocator()->clear();
ERROR: DeprecatedClass - src/TableFinderTrait.php:175:18 - Cake\ORM\TableRegistry is marked deprecated (see https://psalm.dev/098)
$table = TableRegistry::getTableLocator()->get($className);
And invalid namespaces will break in Composer v2
> Fix deprecations.

- tests/TestCase/View/Helper/MigrationHelperTest.php
- tests/comparisons/Diff/addremove/the_diff_add_remove_mysql.php
- tests/comparisons/Diff/simple/the_diff_simple_mysql.php
- tests/comparisons/Diff/the_diff_mysql.php
- tests/comparisons/Migration/test_auto_id_disabled_snapshot.php
- tests/comparisons/Migration/test_not_empty_snapshot.php
- tests/comparisons/Migration/test_plugin_blog.php
The schema reflection changed in CakePHP to accomodate mysql8 not supporting lengths and lengths only being used for display in mysql5.6+.
Because the serialized snapshot data contains lengths all those values are updated in this diff.
> Fix failing mysql tests.

- src/ConfigurationTrait.php
`default_database` was deprecated and renamed to `default_environment` in the 0.12.0 release to better describe what it is that it actually does/mean.
Related upstream PR: https://github.com/cakephp/phinx/pull/1689
> Update deprecated default_database to default_environment

- docs/en/index.rst
- src/Util/ColumnParser.php
Refs https://github.com/dereuromark/cakephp-geo/issues/55
I actually used float here usually. Is there any reason to favor decimal here? Since this isn't about this kind of precision as with money or alike.
> Allow also short forms lat/lng as they are commonly used.

- src/CakeManager.php
- src/Command/Phinx/Status.php
Missing migrations end up as null instead of false
(int) 1 => [
'missing' => true,
'status' => 'up',
'id' => '20150913000236',
'name' => null
],
Might be a recent change
Either way, any empty value should suffice as check to avoid
Exception: str_pad() expects parameter 1 to be string, null given
errors
> Fix missing migration

- src/Command/BakeSimpleMigrationCommand.php
Currently if you wish to override say `templates/bake/element/add-foreign-keys.twig` you would need to do so by placing this file in the app's `templates/bake/element`, but if you are building a plugin/theme and you wish to override `templates/bake/element/add-foreign-keys.twig` you can not without also extending and overriding some class files like `BakeSimpleMigrationCommand.php` for example. Currently the theme is not passed down to the TemplateRenderer so you can not override a template using a theme. Example: currently executing something like `bin/cake bake migration_diff AlterSomething -t MyTheme` would always use `templates/bake/element/add-foreign-keys.twig` from cakephp/migrations not mypackage/my-theme.
> Passing the theme to the TemplateRenderer

- composer.json
- src/TestSuite/ConfigReader.php
- src/TestSuite/Migrator.php
- tests/MigratorTestTrait.php
- tests/TestCase/TestSuite/ConfigReaderTest.php
- tests/TestCase/TestSuite/MigratorTest.php
- tests/test_app/Plugin/BarPlugin/config/Migrations/20200208100000_bar_migration.php
- tests/test_app/Plugin/FooPlugin/config/Migrations/20200208100000_foo_migration.php
Implements the solution to issue #487 in the lines of the (CakePHP Test Migrator)[https://github.com/vierge-noire/cakephp-test-migrator].
> Issue #487 Create the test schema with migrations (Draft)

- .github/workflows/ci.yml
- composer.json
- phpcs.xml.dist
- psalm.xml
- src/CakeAdapter.php
- src/Command/BakeMigrationDiffCommand.php
- src/Command/BakeSeedCommand.php
- src/Command/Phinx/MarkMigrated.php
- src/TestSuite/ConfigReader.php
- src/TestSuite/Migrator.php
- src/View/Helper/MigrationHelper.php
- tests/MigratorTestTrait.php
- tests/TestCase/Command/BakeMigrationDiffCommandTest.php
- tests/TestCase/Command/BakeMigrationSnapshotCommandTest.php
- tests/TestCase/Command/CompletionTest.php
- tests/TestCase/Command/Phinx/CacheBuildTest.php
- tests/TestCase/Command/Phinx/CacheClearTest.php
- tests/TestCase/TestSuite/ConfigReaderTest.php
- tests/TestCase/TestSuite/MigratorTest.php
- tests/TestCase/View/Helper/MigrationHelperTest.php
- tests/bootstrap.php
- tests/test_app/Plugin/BarPlugin/config/Migrations/20200208100000_bar_migration.php
- tests/test_app/Plugin/FooPlugin/config/Migrations/20200208100000_foo_migration.php
* Do a few fixups for #488 
* Port CI configuration to GitHub Actions as travis is on the way out.
> Fixups from Migrator pull request, and CI to GitHub Actions

- src/TestSuite/Migrator.php
This should be setup by including the `PHPUnitExtension` extension.
If a migration is referencing a test connection, it should be already be configured in the bootstrap.
> Remove connection aliasing from Migrator

- src/ConfigurationTrait.php
Resolves https://github.com/cakephp/migrations/issues/511
As core does, the migration plugin should only try to create dirs in debug mode.
> Only create dirs in debug mode
