cakephp/migrations

src/Template/Bake/config/migration.ctp

This fixes some pretty wayward whitespace and uses the features bake provides to make the template easier to read/maintain.

Update bake template

---

README.md

For the terminally short of attention, show how to create your first (populated) migration file first, and _then_ describe how to create an empty migration.
It's only reordering two sections but somehow I missed that there _was_ a usable bake option until today - and possibly other's don't know either.

Say how to start first

---

composer.json
src/Shell/MigrationsShell.php

Also locking version to something we know is stable for us.

Listing all possible options from phinx as valid option in the shell.

---

src/Shell/Task/MigrationSnapshotTask.php
src/Shell/Task/MigrationTask.php
src/Template/Bake/config/snapshot.ctp
src/View/Helper/MigrationHelper.php
tests/Fixture/CompositePkFixture.php
tests/Fixture/SpecialPkFixture.php
tests/TestCase/Shell/Task/MigrationSnapshotTaskTest.php
tests/comparisons/Migration/testNotEmptySnapshot.php

Updates the migration snapshot task to take into account non-default primary key fields.

Update migration snapshot task

---

README.md

fix migration_snapshot command

fix migration_snapshot command

---

.travis.yml
tests/Fixture/CompositePkFixture.php

Add travis test against lower dependancy version

---

src/ConfigurationTrait.php

Fixed hardcoded "default" connection on bootstrap.

---

src/Shell/Task/MigrationSnapshotTask.php
src/Shell/Task/MigrationTask.php

fixed:  hierarchy of namespace in plugin name

fixed:  hierarchy of namespace in plugin name

---

composer.json
src/CakeAdapter.php
src/ConfigurationTrait.php
tests/bootstrap.php

Also aliasing the 'default' connection so that seeding databases can work
more seamlessly.
Fixes #83

Using our own adapter to avoid issues with transactions.

---

tests/TestCase/MigrationsTest.php

This is to ensure that whatever the db engine used to bake a migration file, the resulting file can be migrated across all supported db engines.

Add a test that migrates the snapshot comparisons migrations

---

src/Shell/Task/MigrationTask.php
tests/TestCase/Shell/Task/MigrationTaskTest.php

Fixing the #133 for the `RemoveFieldFromTable`.

fixing MigrationTask#detectAction bug for removing field

---

tests/TestCase/Shell/Task/MigrationSnapshotTaskTest.php
tests/bootstrap.php

Add a test for PR #153

---

composer.json
src/CakeAdapter.php
src/Shell/Task/SimpleMigrationTask.php

Super-seeds #159.
Applies the fix from @robmorgan, update a namespace that was changed in phinx and pinned to a specific phinx version in composer.

Supports phinx 0.5.0

---

src/Shell/Task/MigrationSnapshotTask.php

Closes #163
It was a public method, so it's possible someone somewhere for some reason extended the class and is using it their own way, but I don't know how much of a concern that is.

Remove method that attempts to match plugin tables

---

src/Shell/Task/SimpleMigrationTask.php
tests/TestCase/Shell/Task/MigrationSnapshotTaskTest.php

Camelize migration filename

---

README.md
composer.json
src/Command/Seed.php
src/ConfigurationTrait.php
src/MigrationsDispatcher.php
src/Shell/MigrationsShell.php
src/Shell/Task/SeedTask.php
src/Template/Bake/Seed/seed.ctp
tests/TestCase/Command/SeedTest.php
tests/TestCase/Shell/Task/SeedTaskTest.php
tests/comparisons/Migration/pgsql/test_auto_id_disabled_snapshot_pgsql.php
tests/comparisons/Migration/pgsql/test_not_empty_snapshot_pgsql.php
tests/comparisons/Seeds/testBasicBaking.php
tests/test_app/config/AltSeeds/NumbersAltSeed.php
tests/test_app/config/Seeds/NumbersSeed.php

Follow up to #179 
This implements the command in the MigrationsShell
Once everything is okay, we should start working on documenting everything (baking seeds and running the command).

Seed command

---

.travis.yml
phpunit.xml.dist

Mainly what @lorenzo did with the core issue in PR https://github.com/cakephp/cakephp/pull/7940

Make Coveralls work again

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
README.md

Add GitHub helper files :
- ISSUE_TEMPLATE : Taken from the core and slightly modified to match requirements from this repo
- PULL_REQUEST_TEMPLATE : Taken from the core (with link changed)
- CONTRIBUTING : Taken from the core (with links changed)
I also wiped clean the README to follow the changes made in https://github.com/cakephp/docs/pull/3737 where the purpose was to have one and only one place where to find the doc for the plugin to ease the update process.

Add GitHub helper files and update the README

---

composer.json
tests/comparisons/Migration/test_auto_id_disabled_snapshot56.php
tests/comparisons/Migration/test_not_empty_snapshot56.php
tests/comparisons/Migration/test_plugin_blog56.php

It has been released mostly because of https://github.com/robmorgan/phinx/issues/803

bump to sphinx 0.5.3

---

src/AbstractMigration.php

The actual type then is Migrations\Table.

Use correct return type.

---

src/Command/Migrate.php
src/Command/Rollback.php
src/Shell/MigrationsShell.php
src/Shell/Task/MigrateTask.php
src/Shell/Task/MigrationSnapshotTask.php
src/Shell/Task/RollbackTask.php
src/Shell/Task/SnapshotTrait.php
tests/TestCase/Shell/MigrationShellTest.php
tests/TestCase/Shell/Task/CommandTaskTest.php
tests/TestCase/Shell/Task/MigrationSnapshotTaskTest.php
tests/bootstrap.php

This option is available when migrating, rolling back or baking a snapshot.
Refs #256 and #252

Add an option that allows to skip the dump file generation

---

src/Shell/Task/MigrationDiffTask.php
src/View/Helper/MigrationHelper.php
tests/comparisons/Diff/addremove/the_diff_add_remove_mysql.php
tests/comparisons/Diff/addremove/the_diff_add_remove_pgsql.php
tests/comparisons/Diff/simple/the_diff_simple_mysql.php
tests/comparisons/Diff/simple/the_diff_simple_pgsql.php
tests/comparisons/Diff/the_diff.php
tests/comparisons/Diff/the_diff_mysql.php
tests/comparisons/Diff/the_diff_pgsql.php

Added 'after' attribute to migration_diff.
Refs #276

Add 'after' attribute to migration_diff

---

src/Util/ColumnParser.php

Update ColumnParser for the `_at` suffix

---

.travis.yml
composer.json
tests/TestCase/Shell/Task/CommandTaskTest.php
tests/TestCase/View/Helper/MigrationHelperTest.php
tests/bootstrap.php

They were removed while getting rid of php5.4
Also added PHP 7.1 like in other repos

Re-add the tests against the lower php deps

---

composer.json
src/AbstractSeed.php
src/CakeAdapter.php
src/Command/Create.php
src/Command/MarkMigrated.php
src/Command/Seed.php
src/Migrations.php
src/Table.php
tests/CommandTester.php
tests/TestCase/Command/CreateTest.php
tests/TestCase/Command/DumpTest.php
tests/TestCase/Command/MarkMigratedTest.php
tests/TestCase/Command/SeedTest.php
tests/TestCase/Command/StatusTest.php
tests/TestCase/ConfigurationTraitTest.php

* Updated dependency version in composer.json
* Added missing methods to CakeAdapter

Upgrade robmorgan/phinx to v0.8.1

---

src/Shell/MigrationsShell.php
src/Shell/Task/DumpTask.php

See cakephp/bake#362 and cakephp/cakephp#11272

Add a missing task

---

README.md

The details are exactly one line down.

More generic main header

---

src/Shell/Task/MigrationSnapshotTask.php
src/Shell/Task/SeedTask.php
src/Shell/Task/SimpleMigrationTask.php

Fix deprecation error "Deprecated Error: ConsoleOptionParser::description() is deprecated"

Fix deprecation error for cakePHP 3.6

---

composer.json

Never hard-lock a patch version.

---

src/Shell/Task/SeedTask.php
src/Shell/Task/SimpleMigrationTask.php
src/TableFinderTrait.php

Reverts cakephp/migrations#378
We can revert the revert of the valid part.

Revert "Updated calls to deprecated Plugin::loaded method"

---

.gitignore
composer.json
src/ConfigurationTrait.php
src/Plugin.php
src/Shell/Task/SeedTask.php
src/Shell/Task/SimpleMigrationTask.php
src/TableFinderTrait.php
src/Util/UtilTrait.php
tests/TestCase/ConfigurationTraitTest.php
tests/TestCase/Shell/Task/MigrationSnapshotTaskTest.php
tests/TestCase/Shell/Task/SeedTaskTest.php
tests/TestCase/View/Helper/MigrationHelperTest.php
tests/bootstrap.php
tests/test_app/Plugin/TestBlog/src/Plugin.php

Fixed deprecations using my upgrade tool
bin/cake upgrade fixture_casing /path/to/cakephp/migrations/
is the plugin name also uppercase? or only the Fixture?

Remove deprecations

---

src/Shell/Task/MigrationDiffTask.php
tests/TestCase/Shell/Task/MigrationDiffTaskTest.php
tests/TestCase/Shell/Task/MigrationSnapshotTaskTest.php
tests/comparisons/Diff/the_diff_mysql.php

Hi!
As promised me and @odan looked into #356 and fixed the unit tests.
I'm sorry I couldn't edit the existing PR and created a new one, shoutouts and credits to @harpax.
This should fix #338.

unsigned and unique detection on creating diff

---

src/View/Helper/MigrationHelper.php

Add 'unique' to $validOptions

---

docs/en/index.rst

Ref: https://github.com/cakephp/migrations/issues/388
Documents are updated to showcase the decimal column usage.

Updating documentation to accomodate new changes

---

src/Shell/MigrationsShell.php

fix phinx version

---

src/Shell/MigrationsShell.php

dont run dump for help command

---

composer.json
src/Command/BaseCommand.php
src/Command/MigrationsCommand.php
tests/CommandTester.php

resolves https://github.com/cakephp/migrations/issues/416

Try phpstan 0.12

---

.gitignore
.travis.yml
composer.json
src/Command/CommandTrait.php
src/Command/Create.php
src/Command/Migrate.php
src/Command/Rollback.php
src/Command/Seed.php
src/TableFinderTrait.php

Properly delegate exit code
Resolves https://github.com/cakephp/migrations/issues/426

Fix exit code delegation.

---

src/TableFinderTrait.php

Resolves https://github.com/cakephp/migrations/issues/424

Fix exception

---

src/Shell/Task/SnapshotTrait.php

temporary fix for SnapshotTrait
whole this should convert to command syntax - i'll convert those
Refs: https://github.com/cakephp/cakephp/issues/14386

use command instead of shell to dispatch

---

phpstan.neon
src/ConfigurationTrait.php
src/Util/SchemaTrait.php

Follow https://github.com/cakephp/migrations/pull/436

Fix phpstan level 3

---

phpstan.neon
src/CakeManager.php
src/Command/CommandTrait.php
src/ConfigurationTrait.php
src/Migrations.php
src/TableFinderTrait.php
src/Util/ColumnParser.php
src/View/Helper/MigrationHelper.php

Using https://github.com/cakephp/phinx/pull/1723

Fix phpstan level 5.

---

.gitignore
.travis.yml
composer.json
docs/en/index.rst
docs/fr/index.rst
docs/ja/index.rst
docs/pt/index.rst
docs/ru/index.rst
src/Command/Phinx/CommandTrait.php
src/Command/Phinx/Create.php
src/Command/Phinx/Migrate.php
src/Command/Phinx/Rollback.php
src/Command/Phinx/Seed.php
src/TableFinderTrait.php
tests/TestCase/Command/TestClassWithSnapshotTrait.php
tests/test_app/Plugin/TestBlog/config/CallSeeds/PluginLettersSeed.php
tests/test_app/Plugin/TestBlog/config/CallSeeds/PluginSubLettersSeed.php
tests/test_app/config/AltSeeds/AnotherNumbersSeed.php
tests/test_app/config/AltSeeds/NumbersAltSeed.php
tests/test_app/config/CallSeeds/DatabaseSeed.php
tests/test_app/config/CallSeeds/LettersSeed.php
tests/test_app/config/CallSeeds/NumbersCallSeed.php
tests/test_app/config/Seeds/NumbersSeed.php

merge master=>3.x (cakePHP 4)

---

tests/TestCase/Command/BakeMigrationCommandTest.php
tests/TestCase/Command/BakeMigrationDiffCommandTest.php
tests/TestCase/Command/BakeMigrationSnapshotCommandTest.php
tests/TestCase/Command/BakeSeedCommandTest.php
tests/TestCase/Command/Phinx/CacheBuildTest.php
tests/TestCase/Command/Phinx/CacheClearTest.php
tests/TestCase/Command/Phinx/CreateTest.php
tests/TestCase/Command/Phinx/MarkMigratedTest.php
tests/TestCase/ConfigurationTraitTest.php
tests/TestCase/MigrationsTest.php
tests/TestCase/Util/ColumnParserTest.php
tests/TestCase/View/Helper/MigrationHelperTest.php

Follow https://github.com/cakephp/migrations/pull/454

Fix namespaces and docblocks.

---

composer.json
src/Plugin.php
templates/bake/config/snapshot.twig
templates/bake/element/create-tables.twig
tests/TestCase/TestCase.php

Closes: #433
exclude bake commands when bake plugin is not installed

[4.x] exclude bake commands

---

src/Util/ColumnParser.php
tests/TestCase/Command/BakeMigrationCommandTest.php

Part of https://github.com/cakephp/migrations/issues/355

Add column length guessing for tiny and small.

---

phpstan.neon
src/Table.php
src/Util/ColumnParser.php
tests/CommandTester.php
tests/TestCase/Command/BakeMigrationDiffCommandTest.php
tests/TestCase/Command/Phinx/CacheBuildTest.php
tests/TestCase/Command/Phinx/CacheClearTest.php
tests/TestCase/Command/Phinx/CreateTest.php
tests/TestCase/Command/Phinx/DumpTest.php
tests/TestCase/Command/Phinx/MarkMigratedTest.php
tests/TestCase/Command/Phinx/SeedTest.php
tests/TestCase/Command/Phinx/StatusTest.php
tests/TestCase/MigrationsTest.php
tests/TestCase/TestCase.php
tests/TestCase/Util/ColumnParserTest.php
tests/TestCase/View/Helper/MigrationHelperTest.php

Follow https://github.com/cakephp/migrations/pull/467

Remove deprecations and fix phpstan in tests

---

.gitignore
.travis.yml
phpunit.xml.dist
src/Command/BakeSeedCommand.php
tests/TestCase/Command/BakeMigrationSnapshotCommandTest.php
tests/TestCase/Command/Phinx/DumpTest.php
tests/TestCase/Command/Phinx/MarkMigratedTest.php
tests/TestCase/View/Helper/MigrationHelperTest.php
tests/bootstrap.php

Lots of failing tests
This cuts down a few of them already.
Together with https://github.com/cakephp/phinx/pull/1927
Also adds better DB autodetect based on db_env config.

Start fixing tests.

---

docs/en/index.rst

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
The best way to propose a feature is to open an issue first and discuss your ideas there before implementing them.
Always follow the [contribution guidelines](https://github.com/cakephp/migrations/blob/master/.github/CONTRIBUTING.md) when submitting a pull request. In particular, make sure existing tests still pass, and add tests for all new behavior. When fixing a bug, you may want to add a test to verify the fix.

Clarify statement about alternative seeder source

---

.github/workflows/ci.yml
src/View/Helper/MigrationHelper.php
tests/TestCase/Command/BakeMigrationDiffCommandTest.php
tests/TestCase/View/Helper/MigrationHelperTest.php
tests/comparisons/Migration/pgsql/test_auto_id_disabled_snapshot_pgsql.php
tests/comparisons/Migration/pgsql/test_not_empty_snapshot_pgsql.php
tests/comparisons/Migration/pgsql/test_plugin_blog_pgsql.php

With mysql and sqlite working, we can add postgres back in.

Add postgres back to test matrix.

---

.github/workflows/ci.yml
composer.json
psalm-baseline.xml
src/Command/BakeSeedCommand.php
src/Plugin.php
src/View/Helper/MigrationHelper.php

* Update tool versions.
* Fix relevant psalm errors.
* Update psalm-baseline.xml

Update static analysis buildss

---

src/Table.php

This should fix #489 as the quoting can't be wrong.
Opening this against 3.next to get CI to run. I'll backport this to master (along with CI changes) if this works.

Use a prepared statement instead of interpolation

---

.github/workflows/ci.yml

Check PHP8

---

phpunit.xml.dist
psalm-baseline.xml
src/TestSuite/Migrator.php
tests/TestCase/Command/BakeMigrationSnapshotCommandTest.php
tests/TestCase/Command/Phinx/CreateTest.php
tests/TestCase/Command/Phinx/DumpTest.php
tests/TestCase/ConfigurationTraitTest.php
tests/TestCase/TestSuite/MigratorTest.php
tests/comparisons/Create/TestCreateChange.php

Similar to cakephp/cakephp#15789

Don't recreate schema when in a phpunit separate process test
